### ISSUE TITLE
Postlink script fails.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/itkwidgets-feedstock#1]
```
LinkError: post-link script failed for package conda-forge::itkwidgets-0.15.1-py36_0
running your command again with `-v` will provide additional information
location of failed script: /srv/conda/bin/.itkwidgets-post-link.sh
==> script messages <==
Traceback (most recent call last):
  File "/srv/conda/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/srv/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/srv/conda/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/srv/conda/lib/python3.6/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/srv/conda/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/srv/conda/lib/python3.6/site-packages/itkwidgets/__init__.py", line 4, in <module>
    from .widget_line_profiler import line_profile
  File "/srv/conda/lib/python3.6/site-packages/itkwidgets/widget_line_profiler.py", line 14, in <module>
    import matplotlib.pyplot as plt
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/srv/conda/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 158, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

It seems that itkwidgets does some imports in its `__init__.py` file, and these dependencies are not available at the time the post-link script is run.

**Comment by SylvainCorlay** [comment]
This causes the package not to be installed successfully in e.g. binders.

I would suggest to completely remove link and unlink scripts and rely on notebook >= 5.4 to be installed and pick up the json file instead.

**Comment by thewtex** [comment]
Closing assuming #2 addressed this.
